buttons almost ready
js-tasks-ru/htmlcss-20210708_work4vit pull request #3
Opened 2021-07-14 01:11 UTC by VitalikS

норм ли так делать положение текста?
долго разбирался как поставить текст ровно по центру кнопки, что почитать?

получается ховер у дизейбл кнопок это норм? стоило ли модификатор дизебл вынести в отдельный селектор? или объединить в button__primary_disable? мне показалось что такое объединение это не совсем по БЭМ

Как быть с opacity текста кнопки? хотел поставить только у элемента кнопка но тогда текст не получает опасити(

транзишены покажу чуть позже

2021-07-14 01:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-14 12:30 UTC, GSemikozov requested changes

2021-07-14 12:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.grid__button {
поскольку эта часть не относится к блоку кнопки как таковой, и при этом код лишь помогает временно проставить внешние отступы у кнопок - можно перенести в style самой хтмл страницы с решением

2021-07-14 12:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__disabled {
все состояния описываем через модификаторы, то есть `.button_disabled`.
отвечая на вопрос - в данном случае opacity работает корректно, в макете тоже вся кнопка полупрозрачная.
и еще - рекомендуется всем disabled элементам проставлять pointer-events: none чтобы пользователь не мог нажать

2021-07-14 12:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button-text {
button-text и button-content реализованы не по БЭМ, ну и кроме того - в них нет необходимости ;)
стили для шрифта можно перенести прямиков в .button, точно так же и паддинг из button-content.
отвечая на еще один вопрос: чтобы текст был по середине, и вертикально, и горизонтально - надо во-первых задать паддинги (со всем сторон), и во-вторых - text-align: center

2021-07-14 12:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    line-height: 18.75px;
дробные пиксели не стоит использовать, даже если такое значение стоит в фигме

2021-07-14 12:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button-text__white {
это тоже лишнее и не по БЭМ (поскольку по факту это модификатор который изменяет цвет, а реализовано как отдельный элемент) - менять цвет будем в контексте общего модификатора - типа кнопки (.button_primary, .button_secondary)

2021-07-14 12:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button-text__grey {
то же самое что и выше

2021-07-14 12:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button-content {
чуть выше написал

2021-07-14 12:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__primary {
все модификаторы - здесь и ниже - пишем через одно нижнее подчеркивание `_`

2021-07-14 12:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__primary:hover {
еще был вопрос о том, есть ли ховер у disabled - нет:) поэтому можно записать так: `.button_primary:hover:not(:disabled)`

2021-07-16 13:36 UTC, VitalikS commented on 03-lection1/01-button/button.css
> +.button__primary:hover {
но ведь disabled у меня задается не через псевдо, а через отдельный селектор, точно ...:not(:disabled) ? не понимаю как оно узнает что у кнопки с .button_disabled определит что она такая

2021-07-16 13:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-16 14:02 UTC, VitalikS commented
`transition: opacity 200ms ease-in-out, background 200ms ease-in-out` вопрос по транзишенам, понимаю что мы свойство опасити позволяет менять стиль через прочность, но зачем мы меняем еще и backgound если он задается в стилях ховера? 

у меня просто vsc почему-то выделяет его красным цветом, как будто он не правильно описан.
(для альтернативной кнопки мы меняем бордер и там редактор не ругается)

2021-07-17 03:08 UTC, VitalikS commented on 03-lection1/01-button/button.css
> +.grid__button {
сделал отдельный файл стиля стрнички, на которой лежат кнопки, перенес все такое туда + добавил флексы из последней лекции

2021-07-17 03:09 UTC, VitalikS commented on 03-lection1/01-button/button.css
> +.button__disabled {
поправил модификатор, а также pointer-events

2021-07-17 03:12 UTC, VitalikS commented on 03-lection1/01-button/button.css
> +.button-text {
переписал код, убрал все лишнее из <button>
ты имеешь в виду что button-text и button-content называются не правильно? и что не может быть двойной вложенности в элементе button?

2021-07-17 03:12 UTC, VitalikS commented on 03-lection1/01-button/button.css
> +    line-height: 18.75px;
окей, поправил, округлил

2021-07-17 03:12 UTC, VitalikS commented on 03-lection1/01-button/button.css
> +.button-text__white {
убрал цвета в модификаторы

2021-07-17 03:13 UTC, VitalikS commented on 03-lection1/01-button/button.css
> +.button-text__grey {
Убрал в модификатор и переписал на переменные

2021-07-17 03:13 UTC, VitalikS commented on 03-lection1/01-button/button.css
> +.button-content {
fixed

2021-07-17 03:13 UTC, VitalikS commented on 03-lection1/01-button/button.css
> +.button__primary {
исправил

2021-07-17 07:56 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button-text {
ага, по бэм это были бы button__text и button__content, но как я сказал в них нет смысла, у нас есть кнопка и в ней может быть только текст, в проекте мы не используем никаких доп элементов в кнопке, поэтому не нужно делать лишние врапперы вокруг текста

2021-07-17 07:57 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__primary:hover {
а псевдо :disabled работает так, что видит, есть ли на кнопке атрибут disabled

2021-07-17 07:59 UTC, GSemikozov commented
> `transition: opacity 200ms ease-in-out, background 200ms ease-in-out` вопрос по транзишенам, понимаю что мы свойство опасити позволяет менять стиль через прочность, но зачем мы меняем еще и backgound если он задается в стилях ховера?
> 
> у меня просто vsc почему-то выделяет его красным цветом, как будто он не правильно описан.
> (для альтернативной кнопки мы меняем бордер и там редактор не ругается)

по поводу транзишнов - анимации будем рассматривать в самом конце курса, но в целом - фон добавлен потому, что мы его хотим менять плавно, не только opacity (чтобы не перечисслять, можно написать `transition: all 200ms ease-in-out`)

2021-07-17 10:01 UTC, VitalikS commented on 03-lection1/01-button/button.css
> +.button__primary:hover {
@GSemikozov Так о том и речь, что у меня в коде нет атрибута disabled..

`.button_primary:hover:not(:disabled)` будет работать в случае `<button class="button button_primary grid-button" disabled>`

Но не для случая `<button class="button button__disabled button_primary grid-button">`

Или я не понял задачи и отключением надо командовать через атрибут, а не через класс?

2021-07-17 10:05 UTC, VitalikS commented on 03-lection1/01-button/button.css
> +.button__primary:hover {
Сейчас `pointer-events: none;` успешно отрубает состояние ховера для кнопки. Так что если смотреть только визуально, то кажется, что можно решить проблему добавив его к `.button__disabled`

2021-07-17 10:45 UTC, VitalikS commented
Добавил стили для аттрибута дисаблед, но закомментил. там сейчас оба варианта решения видны

2021-07-17 13:02 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__primary:hover {
только не button__disabled, а - button_disabled

2021-07-17 13:20 UTC, VitalikS commented on 03-lection1/01-button/button.css
> +.button__primary:hover {
Я тут коряво написал в код такой ошибки нет, но поправил другую)

2021-07-17 13:29 UTC, GSemikozov approved these changes

2021-07-17 13:29 UTC, merged