accordion ready
js-tasks-ru/htmlcss-20210708_work4vit pull request #4
Opened 2021-07-16 15:39 UTC by VitalikS

2021-07-16 15:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-16 15:43 UTC, VitalikS commented
В задаче был пункт "При открытии аккордеона, у тега details добавляется атрибут open" не понял для чего он нужен в решении... тут же можно без него, да?

2021-07-17 13:31 UTC, GSemikozov requested changes

2021-07-17 13:31 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 650px;
если родителя жестко зафиксировали по ширине, детей фиксировать не надо, достаточно родителю паддинги, а дочернему элементы ширину на 100% (у блочных элементов она и так 100%)

2021-07-17 13:31 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 159px;
то же самое - тут можно удалить это свойство

2021-07-17 13:31 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +@keyframes accordOpen {
отрабатывает корректно? о нюансах работы с animation + keyframes мы будет говорить в конце курса

2021-07-17 13:36 UTC, VitalikS commented on 03-lection1/02-accordion/accordion.css
> +@keyframes accordOpen {
На открытие корректно, закрывается без анимации. Но я так понял без js это поправить не выйдет

2021-07-17 13:46 UTC, VitalikS commented on 03-lection1/02-accordion/accordion.css
> +    width: 650px;
поправил

2021-07-17 13:46 UTC, VitalikS commented on 03-lection1/02-accordion/accordion.css
> +    width: 159px;
Поправил

2021-07-17 14:17 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +@keyframes accordOpen {
да, верно, либо высота должна быть указана как фиксированная величина

2021-07-17 14:43 UTC, VitalikS commented on 03-lection1/02-accordion/accordion.css
> +@keyframes accordOpen {
Ну фиксированная высота, не очень удачно с точки зрения разных размеров контента, который может быть внутри, верно?

2021-07-17 14:44 UTC, VitalikS commented
Переписал summary на флекс, чтобы стрелока была внутри

2021-07-19 09:11 UTC, VitalikS commented on 03-lection1/02-accordion/accordion.css
> +@keyframes accordOpen {
Убрал анимацию

2021-07-20 12:20 UTC, GSemikozov approved these changes

2021-07-20 12:20 UTC, merged