histogram ready
js-tasks-ru/htmlcss-20210708_work4vit pull request #6
Opened 2021-07-17 03:03 UTC by VitalikS

нормально ли сделаны margin? или стоило сделать как в header главной страницы box с отступами?

2021-07-17 03:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-20 12:31 UTC, GSemikozov requested changes

2021-07-20 12:31 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histo__button{
.histo__button -> .histo__link

2021-07-20 12:31 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin: 0px 24px 16px 24px;
по краям - это будут внутренние отступы

2021-07-21 15:58 UTC, VitalikS commented on 04-lection2/01-histogram/histogram.css
> +    margin: 0px 24px 16px 24px;
поправил

2021-07-21 15:58 UTC, VitalikS commented on 04-lection2/01-histogram/histogram.css
> +.histo__button{
Переименовал класс

2021-07-23 15:09 UTC, GSemikozov requested changes

2021-07-23 15:09 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin: 0 auto;
марджины договорились на уровне блоков не задавать

2021-07-23 15:09 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    max-height: 27px;
это ограничит возможность добавления длинного текста, лучше так не делать

2021-07-23 15:09 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    flex-flow: row wrap;
скорее nowrap - нам не нужно чтобы колонки переносились)

2021-07-23 15:09 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding: 0px 24px 16px 24px;
чтобы не задавать здесь такие паддинги и у хедера такие марджины - margin: 16px 24px 3px 24px; - лучше один раз определить одинаковые отступы через родителя, то есть прописать паддинги у .histo

2021-07-23 15:50 UTC, VitalikS commented on 04-lection2/01-histogram/histogram.css
> +    margin: 0 auto;
Поправил

2021-07-23 15:50 UTC, VitalikS commented on 04-lection2/01-histogram/histogram.css
> +    margin: 0 auto;
убрал

2021-07-23 15:50 UTC, VitalikS commented on 04-lection2/01-histogram/histogram.css
> +    max-height: 27px;
максимальную высоту убрал, ну у меня проблема с высотой строчного флекса, не понимаю почему он высоты 54px выходят хотя контента у меня там на 30px

вот посмотри https://vitaliks.github.io/htmlcss-20210708_work4vit/04-lection2/01-histogram/

2021-07-23 15:50 UTC, VitalikS commented on 04-lection2/01-histogram/histogram.css
> +    padding: 0px 24px 16px 24px;
поправил

2021-07-23 15:50 UTC, VitalikS commented on 04-lection2/01-histogram/histogram.css
> +    flex-flow: row wrap;
поправил

2021-07-23 16:56 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    max-height: 27px;
уже ответил в личном сообщении - исправлено?)

2021-07-23 17:10 UTC, VitalikS commented on 04-lection2/01-histogram/histogram.css
> +    max-height: 27px;
ДА! ;)

2021-07-24 08:50 UTC, GSemikozov approved these changes

2021-07-24 08:50 UTC, merged